### ISSUE TITLE
Incompatibility with main constructor

### ISSUE THREAD

**Issue by maximeozenne** [hmn53/csharp-extract-interface#1]
Hello,

Your extension is fixing one of the major issue I have with vscode, but unfortunately it doesn't seem to work when we are using main constructors.

Here is a simple example :

![CleanShot 2024-12-06 at 16 08 25](https://github.com/user-attachments/assets/b15675b0-3e89-4b62-9216-b83d4bc2c8d1)

If we use the `Extract interface` feature, we get :

![CleanShot 2024-12-06 at 16 05 46](https://github.com/user-attachments/assets/c28017e3-2c85-487a-9d30-d050cc897936)

But we should get something like this :

![CleanShot 2024-12-06 at 16 09 10](https://github.com/user-attachments/assets/6081281a-784d-401f-bcf4-fa3b555417c4)

Or even :

![CleanShot 2024-12-06 at 16 09 41](https://github.com/user-attachments/assets/c04b49e9-bac2-4c69-ab30-ccae429d7771)

Maybe it's just a configuration I'm missing?

Thanks for your work!

**Comment by hmn53** [comment]
Hi @maximeozenne,
Thanks for pointing that out. I will try to fix this today.

**Comment by hmn53** [comment]
I have fixed this in the new version.
Please update the extension and try now.

**Comment by maximeozenne** [comment]
It works! Thank you very much @hmn53!

**Comment by maximeozenne** [comment]
Hi again @hmn53,

Sorry to bother you again, but it seems like it's not working as expected

2 issues here :

First, the bracket is not at the right place when the main constructor is on several lines :

![CleanShot 2024-12-06 at 23 10 25](https://github.com/user-attachments/assets/28541f6e-5d7f-4539-ab80-df7e339ff43d)

The bracket, which was on the next line before using the `Extract interface` option, was put back at the end of the line, after the interface name

Second, the interface is created, but is totally empty, even if the original class contains public methods :

![CleanShot 2024-12-06 at 23 12 35](https://github.com/user-attachments/assets/90ccd8e3-71bd-45b5-83ab-7dabdaa2a947)

Can you please take a look at it?

Thanks for your reactiveness and again, thanks for your work!

**Comment by hmn53** [comment]
Hi @maximeozenne ,
Can you give an example for a class where the interface is empty?

**Comment by maximeozenne** [comment]
Hi @hmn53, 

Sure! 
First, while I was writing an example for you, I've seen that the extraction was working with synchronous methods.

But the issue seems to come from asynchronous methods.

Here is a simple example :

```
public class TestService(
    IMapper mapper,
    ILogger<TestService> logger)
{
    public async Task Test()
    {
        await Task.Run(() => Console.WriteLine("Test"));
    }

    public async Task Test2()
    {
        await Task.Run(() => Console.WriteLine("Test2"));
    }
}
```

Which gives this interface, after extraction :

```
public interface ITestService 
{

}
```

And with the bracket just after the interface name :
![CleanShot 2024-12-07 at 11 09 29](https://github.com/user-attachments/assets/af59fbeb-48c5-489b-afad-1868cca0d196)

**Comment by hmn53** [comment]
Fixed. Please update and try now.
Thanks

**Comment by maximeozenne** [comment]
Thank you very much!!
